version: '3'
services:
  db: 
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=soj
      - TZ=Asia/Shanghai
    expose:
      - "3306"

  soj-backend: 
    build: ./soj/
    container_name: soj-backend
    ports:
      - "8080:8080"
    links: 
      - db
